doppler_releases = [
    ('linux', 'amd64'), 
    ('linux', 'i386'),
    ('linux', 'arm64'), 
    ('linux', 'armv6'),
    ('linux', 'armv7'), 
    ('openbsd', 'amd64'),
    ('openbsd', 'i386'), 
    ('openbsd', 'arm64'),
    ('openbsd', 'armv6'), 
    ('openbsd', 'armv7'),
    ('freebsd', 'amd64'), 
    ('freebsd', 'arm64'),
    ('freebsd', 'armv6'), 
    ('freebsd', 'armv7'),
    ('netbsd', 'amd64'), 
    ('netbsd', 'i386'),
    ('netbsd', 'armv6'), 
    ('netbsd', 'armv7'),
    ('macOS', 'amd64'), 
    ('macOS', 'arm64'),
    ('windows', 'amd64'), 
    ('windows', 'armv6'),
    ('windows', 'armv7'),
]
